from typing import List, Optional
from pydantic import BaseModel, Field

class AgriNexusState(BaseModel):
    # Image Input
    image_path: str = Field(description="Path to the uploaded image")
    
    # Vision Agent Outputs
    vision_diagnosis: Optional[str] = Field(default=None, description="Detected disease or anomaly")
    vision_confidence: float = Field(default=0.0, description="Confidence score of detection")
    
    # RAG Agent Outputs
    rag_treatment_plan: Optional[str] = Field(default=None, description="Proposed treatment plan from ICAR docs")
    proposed_chemical: Optional[str] = Field(default=None, description="Chemical proposed by RAG")
    current_humidity: float = Field(default=75.0, description="Current humidity from weather API")
    
    # Safety Engine Outputs
    is_safe: bool = Field(default=False, description="Whether the treatment passed C++ validation")
    safe_dosage_ml_per_acre: float = Field(default=0.0, description="Calculated safe dosage")
    safety_warning: Optional[str] = Field(default=None, description="Warnings generated by C++ engine")
    
    # Web3 Agent Outputs
    tx_hash: Optional[str] = Field(default=None, description="Transaction hash of Crop Passport")
    passport_id: Optional[int] = Field(default=None, description="ID of created Crop Passport")
    
    # Voice Agent Outputs
    vernacular_audio_url: Optional[str] = Field(default=None, description="Path or URL to generated audio file")
    translated_text: Optional[str] = Field(default=None, description="Translated treatment text")

    # LangGraph control
    errors: List[str] = Field(default_factory=list, description="Any errors encountered during execution")
